POST localhost:81/api/v1/forum/topic
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="category"

4
--WebAppBoundary--
Content-Disposition: form-data; name="title"

Test topic 3.3
--WebAppBoundary--
Content-Disposition: form-data; name="message"

contenue du meessage dsdsd
###
POST localhost:81/api/v1/forum/message
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="reply"

3
--WebAppBoundary--
Content-Disposition: form-data; name="topic"

1
--WebAppBoundary--
Content-Disposition: form-data; name="message"

contenue du meessage bis ddfdf
mutlti

###
GET localhost:81/api/v1/forum/category/all
###
GET localhost:81/api/v1/forum/category/root
###
GET localhost:81/api/v1/forum/category/1
###
GET localhost:81/api/v1/forum/category/test-cat
###
GET localhost:81/api/v1/forum/category/1/topics?limit=10&offset=1
###
GET localhost:81/api/v1/forum/topic/1
###
GET localhost:81/api/v1/forum/message/1?full=1
###
GET localhost:81/api/v1/forum/messages?full=1&author=1&limit=20&offset=0
###
GET localhost:81/api/v1/user/me
###
GET localhost:81/api/v1/project/all

