<?php

const STATUS_NOTHING = 0;
const STATUS_EMAIL_VERIFIED = 1;
const STATUS_EMAIL_NEWS_LETTER = 1 << 1;

const FORUM_PERMISSION_VIEW_MASK = 0b1111;
const FORUM_PERMISSION_CREATE_MASK = 0b1111 << 4;

const FORUM_PERMISSION_VIEW_EVERYONE = 0b0000;
const FORUM_PERMISSION_VIEW_CONNECTED = 0b0001;
const FORUM_PERMISSION_VIEW_MODERATOR = 0b0010;
const FORUM_PERMISSION_VIEW_ADMIN = 0b0011;

const FORUM_PERMISSION_CREATE_EVERYONE = 0b0000 << 4;
const FORUM_PERMISSION_CREATE_CONNECTED = 0b0001 << 4;
const FORUM_PERMISSION_CREATE_MODERATOR = 0b0010 << 4;
const FORUM_PERMISSION_CREATE_ADMIN = 0b0011 << 4;